/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2018-08-31 08:58:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.diandian;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.babycard.wx.*;
import java.net.URLDecoder;
import com.babycard.dao.*;
import com.babycard.util.*;
import java.util.*;

public final class cognitiveboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

//切换语言
long languageId = new LanguageHttp().getLanguageId(request);
long languageId_2 = new LanguageHttp().getLanguageId_2(request);

Card c = (Card)request.getAttribute("card");
Collection cardColl = (Collection)request.getAttribute("cardColl");

int nums = cardColl.size();

Kehu k = new KehuUtil().getKehu(request, response);

String autoplay="0";
if(request.getParameter("autoplay")!=null)
	autoplay="1";

String title= c.getMeaning(languageId,c.getCardId())+"_幼儿认知卡片_亲子教育好帮手_卡片点点为您精心准备";
String detail="卡片点点—幼儿语言启蒙教育平台，支持中英双语音，法德日韩俄等全球主流26种以上的语言";
String cardImg = "http://www.suyufuwu.com";
if(c.getImg().indexOf("gif")!=-1 && c.getSecondPic()!=null)
	cardImg+="/"+c.getSecondPic();
else
	cardImg+=c.getImg();

System.out.println(cardImg);

      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>");
      out.print(title);
      out.write("</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("    \tpadding: 0;\r\n");
      out.write("\t}\r\n");
      out.write("    .page{\r\n");
      out.write("    \twidth: 100%;\r\n");
      out.write("    \theight: 100%;\r\n");
      out.write("    \tposition: absolute;\r\n");
      out.write("    \ttop: 0;\r\n");
      out.write("    \tleft: 0;\r\n");
      out.write("    \tbackground: url(");

    	if(c.getSecondPic()!=null && c.getSecondPic().length()>10){
    		out.print("/"+c.getSecondPic());
    	}else{
    		out.print("/diandian/frame/home-18.jpg");
    	}
    	
      out.write(");\r\n");
      out.write("    \tbackground-size: cover;\r\n");
      out.write("    }\r\n");
      out.write("\t.board{\r\n");
      out.write("\t\t\r\n");
      out.write("\t    height: 100%;\r\n");
      out.write("\t    background-size: cover;\r\n");
      out.write("\t}\r\n");
      out.write("\ta{\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t    color:#524f4f;\r\n");
      out.write("\t}\r\n");
      out.write("\t.item{\r\n");
      out.write("\t\twidth: 18rem;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t}\r\n");
      out.write("\t.itemimg{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.magrginbottom{\r\n");
      out.write("\t\tmargin-bottom: 5rem;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.item span{\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t    width: 100%;\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t    color: #584307;\r\n");
      out.write("\t    font-size: 2rem;\r\n");
      out.write("\t    line-height: 3rem;\r\n");
      out.write("\t}\r\n");
      out.write("\t.spanline1{\r\n");
      out.write("\t\tmargin-top:-4.2rem;\r\n");
      out.write("\t}\r\n");
      out.write("\t.spanline2{\r\n");
      out.write("\t\tmargin-top:-0.5rem;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.opacityShadow{\r\n");
      out.write("\t\topacity: 0.5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.boxShadow{\r\n");
      out.write("\t\tbox-shadow: 0.2rem 0.2rem 0.3rem rgba(0, 0, 0, 0.1);\r\n");
      out.write("\t}\r\n");
      out.write("\t.mainboard{\r\n");
      out.write("\t\tbackground: white;\r\n");
      out.write("    \tposition: absolute;\r\n");
      out.write("    \twidth: 80%;\r\n");
      out.write("    \ttop: 9%;\r\n");
      out.write("    \tz-index: 9999999999;\r\n");
      out.write("    \tborder-radius: 1rem;\r\n");
      out.write("   \t\tmargin-left: 10%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.mainboard span{\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t    width: 100%;\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t    color: #584307;\r\n");
      out.write("\t    font-size: 4rem;\r\n");
      out.write("\t    padding-bottom: 4rem;\r\n");
      out.write("\t}\r\n");
      out.write("\t.headspan{\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t    width: 100%;\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t    color: #584307;\r\n");
      out.write("\t    font-size: 4rem;\r\n");
      out.write("\t    padding-bottom: 4rem;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.cancelimg{\r\n");
      out.write("\t\tbottom: -10%;\r\n");
      out.write("\t    position: absolute;\r\n");
      out.write("\t    left: 46%;\r\n");
      out.write("\t    width: 10%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.effecthidden{\r\n");
      out.write("\t\tbackground: url(/card/frame/sound.gif);\r\n");
      out.write("\t    background-size: 10rem 10rem;\r\n");
      out.write("\t    display: inline-block;\r\n");
      out.write("\t    width: 10rem;\r\n");
      out.write("\t    height: 10rem;\r\n");
      out.write("\t    position: absolute;\r\n");
      out.write("\t    top: 1rem;\r\n");
      out.write("\t    right: 1rem;\r\n");
      out.write("\t    border-radius: 0.5rem;\r\n");
      out.write("\t}\r\n");
      out.write("\t.arrow{\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("    \tbottom: 1rem;\r\n");
      out.write("    \twidth: 5rem;\r\n");
      out.write("    }\r\n");
      out.write("    .return{\r\n");
      out.write("\t\tleft: 10%;\r\n");
      out.write("\t\ttop:0%;\r\n");
      out.write("\t\twidth:100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.headnum{\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tbottom:0;\r\n");
      out.write("\t}\r\n");
      out.write("\t.picarrow{\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t    top: 50%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.picarrow img{\r\n");
      out.write("\t\twidth:7rem;\r\n");
      out.write("\t}\r\n");
      out.write("\t.leftpicarrow{\r\n");
      out.write("\t\tleft: -10%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.rightpicarrow{\r\n");
      out.write("    \tleft: 95%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.headbar{\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("    \ttop: ");
if(autoplay.equals("0"))out.print("0");else out.print("-10%");
      out.write(";\r\n");
      out.write("    \tpadding:1rem;\r\n");
      out.write("    \tz-index:99999;\r\n");
      out.write("\t}\r\n");
      out.write("\t.hearbarimg{\r\n");
      out.write("\t\theight:7rem;\r\n");
      out.write("\t}\r\n");
      out.write("\t.timediv{\r\n");
      out.write("\t\twidth: 0%;\r\n");
      out.write("    \theight: 0.3rem;\r\n");
      out.write("    \tposition: absolute;\r\n");
      out.write("    \tbottom: 0;\r\n");
      out.write("    \tbackground: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t.xialadiv{\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("    \ttop: -10%;\r\n");
      out.write("    \ttext-align:center;\r\n");
      out.write("    \tz-index: 99999;\r\n");
      out.write("    \twidth: 100%;\r\n");
      out.write("    \tdisplay:block;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"load()\">\r\n");
      out.write("\t<div class=\"page\" style=\"background-size: cover;\">\r\n");
      out.write("\t\t<div class=\"xialadiv\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"xiala\">\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"/diandian/frame/shou.png\" style=\"width:12rem;\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"headbar\">\r\n");
      out.write("\t\t\t<a href=\"/diandian/\">\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"/diandian/frame/h0.png\" class=\"hearbarimg\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:history.back();\">\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"/diandian/frame/h1.png\" class=\"hearbarimg\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"/card/cardlist.html?cardId=");
      out.print(c.getCardId() );
      out.write("&pre=t\" >\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"/diandian/frame/h6.png\" class=\"hearbarimg\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"autoplay\">\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"/diandian/frame/h2");

				if(request.getParameter("autoplay")!=null)
					out.print("_1");
				
      out.write(".png\" class=\"hearbarimg autoimg\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"/card/cardlist.html?cardId=");
      out.print(c.getCardId() );
      out.write("&next=t\" >\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"/diandian/frame/h7.png\" class=\"hearbarimg\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"test_iop.html?cardId=");
      out.print(c.getCardId() );
      out.write("\" >\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"/diandian/frame/h3.png\" class=\"hearbarimg\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"");

						if(Long.parseLong(request.getAttribute("isFav").toString())==0){
							
      out.write("/diandian/frame/h4_1.png");

						}else{
							
      out.write("/diandian/frame/h4.png");

						}
				
      out.write("\" class=\"hearbarimg favImg\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t");

    		if(k.getId()==c.getkId() ||k.getGuanlibiaoji()==1){
    		
      out.write("\r\n");
      out.write("\t\t\t<a href=\"carddetail.html?cardId=");
      out.print(c.getCardId() );
      out.write("\" >\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"/diandian/frame/h5.png\" class=\"hearbarimg\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t<a href=\"/diandian/setup.html?cardId=");
      out.print(c.getCardId() );
      out.write("\" >\r\n");
      out.write("\t\t\t\t<img alt=\"\" src=\"/diandian/frame/h5.png\" class=\"hearbarimg\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"board\">\r\n");
      out.write("\t\t\t<span class=\"headnum headspan\">1/");
      out.print(nums );
      out.write("</span>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t");

    		if(false && (k.getId()==c.getkId() ||k.getGuanlibiaoji()==1)){
    		
      out.write("\r\n");
      out.write("    \t\t<a href=\"/card/carddetail.html?cardId=");
      out.print(c.getCardId());
      out.write("\">\t\r\n");
      out.write("\t\t\t\t<img src=\"/diandian/frame/footer-1_active.png\" class=\"arrow return\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--a href=\"/diandian/\"  class=\"headmenu\" style=\"left: 1rem;\r\n");
      out.write("    \t\t\">\r\n");
      out.write("\t\t\t\t<img src=\"/diandian/frame/menu.png\" style=\"width: 8rem;\" class=\"boxShadow\">\r\n");
      out.write("\t\t\t</a-->\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    ");

		    CardPic first = (CardPic)cardColl.iterator().next();
		    
      out.write("\r\n");
      out.write("\t\t\t<div class=\"mainboard boxShadow\"  style=\"");
if(c.getShowType()==1)out.print("display:none");
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(first.getImgurl());
      out.write("\" class=\"itemimg magrginbottom\" >\r\n");
      out.write("\t\t\t\t\t<span class=\"spanline1\">");
      out.print(CardMeaning.getStaticCard(first.getPicId(), languageId).getMeaning() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"spanline2\">");
      out.print(CardMeaning.getStaticCard(first.getPicId(), languageId_2).getMeaning() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<img class=\"cancelimg\" src=\"/diandian/frame/cancel.png\" style=\"");
if(c.getShowType()==0)out.print("display:none");
      out.write("\">\r\n");
      out.write("\t\t\t\t\t");

					if(first.getSound()!=null && first.getSound().length()>2){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"effecthidden boxShadow\">\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"picarrow leftpicarrow\" >\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"\" src=\"/diandian/frame/left.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"picarrow rightpicarrow\" >\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"\" src=\"/diandian/frame/right.png\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			int index=1;
			int j=1;
			Iterator picit = cardColl.iterator();
			while(picit.hasNext()){
				CardPic fpic = (CardPic)picit.next();
				
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"item\" id=\"item");
      out.print(fpic.index );
      out.write("\" index=\"");
      out.print(fpic.index );
      out.write("\" picId=\"");
      out.print(fpic.getPicId() );
      out.write("\" style=\"top: ");
      out.print(fpic.getTopP());
      out.write("%;left: ");
      out.print(fpic.getLeftP());
      out.write("%;width: ");
      out.print(fpic.getWidthP());
      out.write("rem;");
if(c.getShowType()==0)out.print("display:none");
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(fpic.getImgurl() );
      out.write("\" class=\"itemimg\"  >\r\n");
      out.write("\t\t\t\t\t<span class=\"spanline1\"  style=\"margin-top:");
      out.print(fpic.getMarginTop());
      out.write("rem;\">");
      out.print(CardMeaning.getStaticCard(fpic.getPicId(), languageId).getMeaning() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"spanline2\"  style=\"margin-top:");
      out.print(fpic.getMarginTop2());
      out.write("rem;\" >");
      out.print(CardMeaning.getStaticCard(fpic.getPicId(), languageId_2).getMeaning() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!--         音效           -->\r\n");
      out.write("       \t\t\t");

  					if(fpic.getSound()!=null && fpic.getSound().length()>2){
  						if(request.getSession().getAttribute("soundFlag")==null ||request.getSession().getAttribute("soundFlag").toString().equals("0")){
  					
      out.write("\r\n");
      out.write("  \t\t\t\t\t\t<audio preload=\"auto\" controls id=\"effect_");
      out.print(fpic.index );
      out.write("\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t<source src=\"/");
      out.print(fpic.getSound() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t</audio>\r\n");
      out.write("\t\t\t\t");
  } 
				}
      out.write("   \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!--         语音           -->\r\n");
      out.write("\t\t\t\t");

				Collection picSoundColl = CardSound.getSoundCollByPicId(fpic.getPicId());
				Iterator picSoundIt = picSoundColl.iterator();
				while(picSoundIt.hasNext()){
					CardSound cs = (CardSound)picSoundIt.next();
					if(cs.getLanguageId()!=1&&cs.getLanguageId()!=0)
						continue;
					if(request.getSession().getAttribute("soundFlag")==null ||request.getSession().getAttribute("soundFlag").toString().equals("0")){
						String sound = cs.getSound();
						if(sound.indexOf("sound")!=-1){
							sound="/card/"+sound;
						}
						if(cs.getLanguageId()==1){
							CardMeaning temp =CardMeaning.getStaticCard(fpic.getPicId(), languageId);
							if(temp.getAmPhMp3()!=null){
								sound=temp.getAmPhMp3();
							}
						}
					
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t<audio controls id=\"sound_");
      out.print(fpic.index);
      out.write('_');
      out.print(cs.getLanguageId());
      out.write("\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t<source src=\"");
      out.print(sound );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</audio>\t\r\n");
      out.write("\t\t\t\t\t");

					}
				}

				
				j++;
				
			}
			
			
			
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"timediv\">\r\n");
      out.write("    \t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar index=");
      out.print(first.index);
      out.write(";\r\n");
      out.write("\tvar autoplay=");
      out.print(autoplay);
      out.write(";\r\n");
      out.write("\tvar times=8500;\r\n");
      out.write("\tvar dwidth=1;\r\n");
      out.write("\tvar stopFlag=0;\r\n");
      out.write("\t\r\n");
      out.write("\tfunction load()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tt=doCurrent();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(autoplay==1){\r\n");
      out.write("\t\t\t$(\".xialadiv\").css({top:'0%'});\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t$(\".xialadiv\").animate({top:'0%'},2000);\r\n");
      out.write("\t\t\t\t$(\".headbar\").animate({top:'-10%'},2000);\r\n");
      out.write("\t\t\t},3000);\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction doCurrent(){\r\n");
      out.write("\t\tif(autoplay==1){\r\n");
      out.write("\t\t\tt=playCurrent();\r\n");
      out.write("\t\t\t$(\".autoimg\").attr(\"src\",\"/diandian/frame/h2_1.png\")\r\n");
      out.write("\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\tauto=next();\r\n");
      out.write("\t\t\t},times);\r\n");
      out.write("\t\t\t$(\".timediv\").css({'width':'0%'});\r\n");
      out.write("\t\t\t$(\".timediv\").animate({width:'100%',opacity:'0.4'},times);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"sound_\"+index+\"_");
      out.print(languageId);
      out.write("\").play();\r\n");
      out.write("\t\t\t},500);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction playCurrent(){\r\n");
      out.write("\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\tdocument.getElementById(\"sound_\"+index+\"_");
      out.print(languageId);
      out.write("\").play();\r\n");
      out.write("\t\t},500);\r\n");
      out.write("\t\tif(document.getElementById(\"effect_\"+index)!=null){\r\n");
      out.write("\t\t\t$(\".effecthidden\").show();\r\n");
      out.write("\t\t\tif(autoplay==1){\r\n");
      out.write("\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\tif(document.getElementById(\"effect_\"+index)!=null)\r\n");
      out.write("\t\t\t\t\t\taudioAutoPlay1(\"effect_\"+index);},4500);\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\".effecthidden\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction audioAutoPlay1(id){\r\n");
      out.write("\t    var audio = document.getElementById(id);\r\n");
      out.write("\t    audio.load();\r\n");
      out.write("\t    audio.play();\r\n");
      out.write("\t    document.addEventListener(\"WeixinJSBridgeReady\", function () {\r\n");
      out.write("\t            audio.play();\r\n");
      out.write("\t    }, false);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction next(){\r\n");
      out.write("\t\tif(stopFlag==1){\r\n");
      out.write("\t\t\tstopFlag=0;\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tif(index<");
      out.print(nums);
      out.write("){\r\n");
      out.write("\t\t\tindex=parseInt(index)+1;\r\n");
      out.write("\t\t\tt=changeItem();\r\n");
      out.write("\t\t\tif(autoplay==1){\r\n");
      out.write("\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\tauto=next();\r\n");
      out.write("\t\t\t\t},times);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(dwidth==1){\r\n");
      out.write("\t\t\t\t\tdwidth=0;\r\n");
      out.write("\t\t\t\t\t$(\".timediv\").animate({width:'0%'},times);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tdwidth=1;\r\n");
      out.write("\t\t\t\t\t$(\".timediv\").animate({width:'100%'},times);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif(autoplay==0){\r\n");
      out.write("\t\t\t\tlocation.href=\"/card/cardlist.html?cardId=");
      out.print(c.getCardId());
      out.write("&next=t\";\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tlocation.href=\"/card/cardlist.html?cardId=");
      out.print(c.getCardId());
      out.write("&next=t&autoplay=t\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction pre(){\r\n");
      out.write("\t\tif(index>1){\r\n");
      out.write("\t\t\tindex=index-1;\r\n");
      out.write("\t\t\tt=changeItem();\t\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif(autoplay==0){\r\n");
      out.write("\t\t\t\tlocation.href=\"/card/cardlist.html?cardId=");
      out.print(c.getCardId());
      out.write("&pre=t\";\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tlocation.href=\"/card/cardlist.html?cardId=");
      out.print(c.getCardId());
      out.write("&pre=t&autoplay\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changeItem(){\r\n");
      out.write("\t\t$(\".headnum\").text(index+\"/");
      out.print(nums);
      out.write("\");\r\n");
      out.write("\t\t$(\".mainboard\").children(\".itemimg\").attr(\"src\",$(\"#item\"+index).children(\"img\").attr(\"src\"));\r\n");
      out.write("\t\tconsole.log($(\"#item\"+index).children(\"spanline1\").text());\r\n");
      out.write("\t\t$(\".mainboard\").children(\".spanline1\").text($(\"#item\"+index).children(\".spanline1\").text());\r\n");
      out.write("\t\t$(\".mainboard\").children(\".spanline2\").text($(\"#item\"+index).children(\".spanline2\").text());\r\n");
      out.write("\t\t$(\".mainboard\").show();\r\n");
      out.write("\t\tt=playCurrent();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\".cancelimg\").click(function(){\r\n");
      out.write("\t\t\t$(\".item\").removeClass(\"opacityShadow\");\r\n");
      out.write("\t\t\t$(\".mainboard\").hide();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".effecthidden\").click(function(){\r\n");
      out.write("\t\t\t$(this).removeClass(\"boxShadow\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"effect_\"+index).play();\r\n");
      out.write("\t\t\tsetTimeout(function(){ \r\n");
      out.write("\t\t\t\t$(\".effecthidden\").addClass(\"boxShadow\");\r\n");
      out.write("\t\t\t}, 2000);\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".xialadiv\").click(function(){\r\n");
      out.write("\t\t\t$(\".xialadiv\").animate({top:'-10%'},1000);\r\n");
      out.write("\t\t\t$(\".headbar\").animate({top:'0%'},1000);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t$(\".xialadiv\").animate({top:'0%'},2000);\r\n");
      out.write("\t\t\t\t$(\".headbar\").animate({top:'-10%'},2000);\r\n");
      out.write("\t\t\t},times);\r\n");
      out.write("\t\t})\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".spanline1\").click(function(){\r\n");
      out.write("\t\t\tdocument.getElementById(\"sound_\"+index+\"_");
      out.print(languageId);
      out.write("\").play();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".spanline2\").click(function(){\r\n");
      out.write("\t\t\tdocument.getElementById(\"sound_\"+index+\"_");
      out.print(languageId_2);
      out.write("\").play();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".item\").click(function(){\r\n");
      out.write("\t\t\tindex=$(this).attr(\"index\");\r\n");
      out.write("\t\t\t$(\".item\").addClass(\"opacityShadow\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tt=changeItem();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".autoplay\").click(function(){\r\n");
      out.write("\t\t\tif(autoplay==0){\r\n");
      out.write("\t\t\t\tautoplay=1;\r\n");
      out.write("\t\t\t\tt=doCurrent();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tautoplay=0;\r\n");
      out.write("\t\t\t\tstopFlag=1;\r\n");
      out.write("\t\t\t\t$(\".autoimg\").attr(\"src\",\"/diandian/frame/h2.png\")\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar windowHeight = $(window).height(),\r\n");
      out.write("\t\t$body = $(\"body\");\r\n");
      out.write("\t\t$body.css(\"height\", windowHeight); //重要代码\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"body\").on(\"touchstart\", function(e) {\r\n");
      out.write("\t\t\t//e.preventDefault();\r\n");
      out.write("\t\t\tstartX = e.originalEvent.changedTouches[0].pageX,\r\n");
      out.write("\t\t\tstartY = e.originalEvent.changedTouches[0].pageY;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".leftpicarrow\").click(function(){\r\n");
      out.write("\t\t\tt=pre();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".rightpicarrow\").click(function(){\r\n");
      out.write("\t\t\tt=next();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar moveFlag=0;\r\n");
      out.write("\t\t$(\"body\").on(\"touchmove\", function(e) {\r\n");
      out.write("\t\t\t//e.preventDefault();\r\n");
      out.write("\t\t\tmoveEndX = e.originalEvent.changedTouches[0].pageX,\r\n");
      out.write("\t\t\tmoveEndY = e.originalEvent.changedTouches[0].pageY,\r\n");
      out.write("\t\t\tX = moveEndX - startX,\r\n");
      out.write("\t\t\tY = moveEndY - startY;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(moveFlag==0){\r\n");
      out.write("\t\t\t\tmoveFlag=1;\r\n");
      out.write("\t\t\t\tsetTimeout(function(){ \r\n");
      out.write("\t\t\t\t\tmoveFlag=0;\r\n");
      out.write("\t\t\t\t}, 300);\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif ( Math.abs(X) > Math.abs(Y) && X > 25 ) {\r\n");
      out.write("\t\t\t\t\tt=pre();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if ( Math.abs(X) > Math.abs(Y) && X < -25 ) {\r\n");
      out.write("\t\t\t\t\tt=next();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if ( Math.abs(Y) > Math.abs(X) && Y > 0) {\r\n");
      out.write("\t\t\t\t\t//alert(\"top 2 bottom\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if ( Math.abs(Y) > Math.abs(X) && Y < 0 ) {\r\n");
      out.write("\t\t\t\t\t//alert(\"bottom 2 top\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t//alert(\"just touch\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//0表示已收藏\r\n");
      out.write("\t\tvar favFlag=");
      out.print(request.getAttribute("isFav").toString());
      out.write(";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.favImg').on(\"click\", function () {\r\n");
      out.write("\t\t\tif(favFlag==0){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: 'cardlist.html?cardId=");
      out.print(c.getCardId());
      out.write("&favdelete=t',\r\n");
      out.write("\t\t\t\t\tdateType:'json',\r\n");
      out.write("\t\t\t\t    success: function(data){\r\n");
      out.write("\t\t\t\t    \talert('");
      out.print(Menu.getMenu("cancle_fav_succ", languageId) );
      out.write("');\r\n");
      out.write("\t\t\t\t    }\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t\t$(this).attr(\"src\",\"/diandian/frame/h4.png\");\r\n");
      out.write("\t\t\t\tfavFlag=1;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: 'cardlist.html?cardId=");
      out.print(c.getCardId());
      out.write("&favcard=t',\r\n");
      out.write("\t\t\t\t\tdateType:'json',\r\n");
      out.write("\t\t\t\t    success: function(data){\r\n");
      out.write("\t\t\t\t    \talert('");
      out.print(Menu.getMenu("fav_succ", languageId) );
      out.write("');\r\n");
      out.write("\t\t\t\t    }\r\n");
      out.write("\t\t\t   });\r\n");
      out.write("\t\t\t\t$(this).attr(\"src\",\"/diandian/frame/h4_1.png\");\r\n");
      out.write("\t\t\t   favFlag=0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t    });\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t})\r\n");
      out.write("</script>\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");



String url = "http://www.suyufuwu.com/card/cardlist.html?"+ (request.getQueryString()); 
Map<String, String> ret = new AccessToken().webSign(url,request, response);
String appId = KehuUtil.appId;
String timestamp = ret.get("timestamp");
String nonceStr = ret.get("nonceStr");
String signature = ret.get("signature");

if(request.getSession().getAttribute("subscribe")!=null && request.getSession().getAttribute("subscribe").toString().equals("0")){
	request.getSession().removeAttribute("subscribe");
	
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tlocation.href='/diandian/weiguanzhu.jsp';\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");
	
}



      out.write("\r\n");
      out.write("<script typet=\"text/javascript\" src=\"http://res.wx.qq.com/open/js/jweixin-1.2.0.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\t\twx.config({\r\n");
      out.write("                debug: false,////生产环境需要关闭debug模式\r\n");
      out.write("                appId: '");
      out.print(appId );
      out.write("',\r\n");
      out.write("                timestamp: ");
      out.print(timestamp );
      out.write(",\r\n");
      out.write("                nonceStr: '");
      out.print(nonceStr);
      out.write("',\r\n");
      out.write("                signature: '");
      out.print(signature);
      out.write("',\r\n");
      out.write("                jsApiList: [//需要调用的JS接口列表\r\n");
      out.write("                    'checkJsApi',//判断当前客户端版本是否支持指定JS接口\r\n");
      out.write("                    'onMenuShareTimeline',//分享给好友\r\n");
      out.write("                    'onMenuShareAppMessage'//分享到朋友圈\r\n");
      out.write("                ]\r\n");
      out.write("            });   \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("wx.ready(function () {\r\n");
      out.write("    var link = window.location.href;\r\n");
      out.write("    var protocol = window.location.protocol;\r\n");
      out.write("    var host = window.location.host;\r\n");
      out.write("    //分享朋友圈\r\n");
      out.write("    wx.onMenuShareTimeline({\r\n");
      out.write("        title: '");
      out.print(title);
      out.write("',\r\n");
      out.write("        link: link,\r\n");
      out.write("        imgUrl: '");
      out.print(cardImg);
      out.write("',// 自定义图标\r\n");
      out.write("        trigger: function (res) {\r\n");
      out.write("            // 不要尝试在trigger中使用ajax异步请求修改本次分享的内容，因为客户端分享操作是一个同步操作，这时候使用ajax的回包会还没有返回.\r\n");
      out.write("            //alert('click shared');\r\n");
      out.write("        },\r\n");
      out.write("        success: function (res) {\r\n");
      out.write("            //alert('shared success');\r\n");
      out.write("            //some thing you should do\r\n");
      out.write("        },\r\n");
      out.write("        cancel: function (res) {\r\n");
      out.write("            //alert('shared cancle');\r\n");
      out.write("        },\r\n");
      out.write("        fail: function (res) {\r\n");
      out.write("            alert(JSON.stringify(res));\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    //分享给好友\r\n");
      out.write("    wx.onMenuShareAppMessage({\r\n");
      out.write("        title: '");
      out.print(title);
      out.write("', // 分享标题\r\n");
      out.write("        desc: '");
      out.print(detail);
      out.write("', // 分享描述\r\n");
      out.write("        link: link, // 分享链接，该链接域名或路径必须与当前页面对应的公众号JS安全域名一致\r\n");
      out.write("        imgUrl: '");
      out.print(cardImg);
      out.write("', // 自定义图标\r\n");
      out.write("        type: 'link', // 分享类型,music、video或link，不填默认为link\r\n");
      out.write("        dataUrl: '', // 如果type是music或video，则要提供数据链接，默认为空\r\n");
      out.write("        success: function () {\r\n");
      out.write("            // 用户确认分享后执行的回调函数\r\n");
      out.write("        },\r\n");
      out.write("        cancel: function () {\r\n");
      out.write("            // 用户取消分享后执行的回调函数\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    wx.error(function (res) {\r\n");
      out.write("        alert(res.errMsg);\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
